"""initial

Revision ID: 8a66d3e23c2c
Revises: 
Create Date: 2026-04-12 22:58:21.250171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a66d3e23c2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_ticker'), 'symbol', ['ticker'], unique=True)
    op.create_table('earnings_quarter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter_end', sa.Date(), nullable=False),
    sa.Column('eps_actual', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('eps_estimate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('revenue_actual', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('revenue_estimate', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('eps_surprise_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('revenue_surprise_pct', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('eps_result', sa.String(length=16), nullable=False),
    sa.Column('revenue_result', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'fiscal_quarter_end', name='uq_symbol_quarter')
    )
    op.create_index(op.f('ix_earnings_quarter_symbol_id'), 'earnings_quarter', ['symbol_id'], unique=False)
    op.create_table('symbol_sync_state',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbol_sync_state')
    op.drop_index(op.f('ix_earnings_quarter_symbol_id'), table_name='earnings_quarter')
    op.drop_table('earnings_quarter')
    op.drop_index(op.f('ix_symbol_ticker'), table_name='symbol')
    op.drop_table('symbol')
    # ### end Alembic commands ###
